import {
  LeafIcon,
  ShieldIcon,
  DropletIcon,
  FlaskIcon,
  RulerIcon,
  FeatherIcon,
  WindIcon,
  HeartHandIcon,
  RecycleIcon,
  CottonIcon,
  BadgeIcon,
  IndiaFlagIcon,
  WingIcon,
  SparkleIcon,
  ClockIcon,
  LayersIcon,
  DisposeIcon,
  type IconProps,
} from './icons'

export const iconMap: Record<string, (p: IconProps) => JSX.Element> = {
  leaf: LeafIcon,
  shield: ShieldIcon,
  droplet: DropletIcon,
  flask: FlaskIcon,
  ruler: RulerIcon,
  feather: FeatherIcon,
  wind: WindIcon,
  heart: HeartHandIcon,
  recycle: RecycleIcon,
  cotton: CottonIcon,
  badge: BadgeIcon,
  india: IndiaFlagIcon,
  wing: WingIcon,
  sparkle: SparkleIcon,
  clock: ClockIcon,
  layers: LayersIcon,
  dispose: DisposeIcon,
}
